export enum RequestState {
    INITIAL = 'INITIAL',
    APPROVED_MANAGER = 'APPROVED_MANAGER',
    REJECTED_MANAGER = 'REJECTED_MANAGER',
    APPROVED_DIRECTOR = 'APPROVED_DIRECTOR',
    REJECTED_DIRECTOR = 'REJECTED_DIRECTOR',
    REDIRECTED = 'REDIRECTED',
    REJECTED_REDIRECT_DIRECTOR = 'REJECTED_REDIRECT_DIRECTOR',
    END = 'END'
}
